#ifndef SHOAL_INCLUDE_CONFIG_H_
#define SHOAL_INCLUDE_CONFIG_H_

#include "global_utilities.hpp"

// Active Message types
#define AM_SHORT 0x1
#define AM_MEDIUM 0x2
#define AM_LONG 0x4
#define AM_VECTOR 0x6
#define AM_STRIDE 0x5
#define AM_FIFO 0x10
#define AM_ASYNC 0x20
#define AM_REPLY 0x40

// handler macros
#define H_EMPTY 0
#define H_INCR_MEM 1
#define H_ADD 2
#define H_INCR_BAR 3
#define H_WAIT 4

/*******************************************************************************
 * Active Message parameter bit values
*******************************************************************************/

// Header
#define AM_SRC_UPPER 23
#define AM_SRC_LOWER 8
#define AM_DST_UPPER 39
#define AM_DST_LOWER 24
#define AM_PAYLOAD_SIZE_UPPER 55
#define AM_PAYLOAD_SIZE_LOWER 40
#define AM_HANDLER_UPPER 59
#define AM_HANDLER_LOWER 56
#define AM_TYPE_UPPER 7
#define AM_TYPE_LOWER 0
#define AM_HANDLER_ARGS_UPPER 63
#define AM_HANDLER_ARGS_LOWER 60
#define AM_TOKEN_UPPER 63
#define AM_TOKEN_LOWER 48

// Long Strided
#define AM_STRIDE_SIZE_LOWER 0
#define AM_STRIDE_SIZE_UPPER 15
#define AM_STRIDE_BLK_SIZE_LOWER 16
#define AM_STRIDE_BLK_SIZE_UPPER 27
#define AM_STRIDE_BLK_NUM_LOWER 28
#define AM_STRIDE_BLK_NUM_UPPER 39

// Long Vector
#define AM_SRC_VECTOR_NUM_LOWER 0
#define AM_SRC_VECTOR_NUM_UPPER 3
#define AM_DST_VECTOR_NUM_LOWER 4
#define AM_DST_VECTOR_NUM_UPPER 7
#define AM_SRC_VECTOR_SIZE_HEAD_LOWER 8
#define AM_SRC_VECTOR_SIZE_HEAD_UPPER 19
#define AM_DST_VECTOR_SIZE_HEAD_LOWER 20
#define AM_DST_VECTOR_SIZE_HEAD_UPPER 31
#define AM_SRC_VECTOR_SIZE_BODY_LOWER 0
#define AM_SRC_VECTOR_SIZE_BODY_UPPER 11
#define AM_DST_VECTOR_SIZE_BODY_LOWER 0
#define AM_DST_VECTOR_SIZE_BODY_UPPER 11

/*******************************************************************************
 * Active Message parameter bit ranges
*******************************************************************************/

// Header
#define AM_PAYLOAD_SIZE AM_PAYLOAD_SIZE_UPPER,AM_PAYLOAD_SIZE_LOWER
#define AM_SRC AM_SRC_UPPER,AM_SRC_LOWER
#define AM_DST AM_DST_UPPER,AM_DST_LOWER
#define AM_HANDLER AM_HANDLER_UPPER,AM_HANDLER_LOWER
#define AM_TYPE AM_TYPE_UPPER,AM_TYPE_LOWER
#define AM_HANDLER_ARGS AM_HANDLER_ARGS_UPPER,AM_HANDLER_ARGS_LOWER
#define AM_TOKEN AM_TOKEN_UPPER,AM_TOKEN_LOWER

// Long strided
#define AM_STRIDE_SIZE AM_STRIDE_SIZE_UPPER,AM_STRIDE_SIZE_LOWER
#define AM_STRIDE_BLK_SIZE AM_STRIDE_BLK_SIZE_UPPER,AM_STRIDE_BLK_SIZE_LOWER
#define AM_STRIDE_BLK_NUM AM_STRIDE_BLK_NUM_UPPER,AM_STRIDE_BLK_NUM_LOWER

// Long Vector
#define AM_SRC_VECTOR_NUM AM_SRC_VECTOR_NUM_UPPER,AM_SRC_VECTOR_NUM_LOWER
#define AM_DST_VECTOR_NUM AM_DST_VECTOR_NUM_UPPER,AM_DST_VECTOR_NUM_LOWER
#define AM_SRC_VECTOR_SIZE_HEAD AM_SRC_VECTOR_SIZE_HEAD_UPPER,AM_SRC_VECTOR_SIZE_HEAD_LOWER
#define AM_DST_VECTOR_SIZE_HEAD AM_DST_VECTOR_SIZE_HEAD_UPPER,AM_DST_VECTOR_SIZE_HEAD_LOWER
#define AM_SRC_VECTOR_SIZE_BODY AM_SRC_VECTOR_SIZE_BODY_UPPER,AM_SRC_VECTOR_SIZE_BODY_LOWER
#define AM_DST_VECTOR_SIZE_BODY AM_DST_VECTOR_SIZE_BODY_UPPER,AM_DST_VECTOR_SIZE_BODY_LOWER

/*******************************************************************************
 * Active Message parameter sizes
*******************************************************************************/

// Header
#define AM_PAYLOAD_SIZE_WIDTH (AM_PAYLOAD_SIZE_UPPER-AM_PAYLOAD_SIZE_LOWER+1)
#define AM_SRC_WIDTH (AM_SRC_UPPER-AM_SRC_LOWER+1)
#define AM_DST_WIDTH (AM_DST_UPPER-AM_DST_LOWER+1)
#define AM_HANDLER_WIDTH (AM_HANDLER_UPPER-AM_HANDLER_LOWER+1)
#define AM_TYPE_WIDTH (AM_TYPE_UPPER-AM_TYPE_LOWER+1)
#define AM_HANDLER_ARGS_WIDTH (AM_HANDLER_ARGS_UPPER-AM_HANDLER_ARGS_LOWER+1)
#define AM_TOKEN_WIDTH (AM_TOKEN_UPPER-AM_TOKEN_LOWER+1)
#define AM_STRIDE_SIZE_WIDTH (AM_STRIDE_SIZE_UPPER-AM_STRIDE_SIZE_LOWER+1)
#define AM_STRIDE_BLK_SIZE_WIDTH (AM_STRIDE_BLK_SIZE_UPPER-AM_STRIDE_BLK_SIZE_LOWER+1)
#define AM_STRIDE_BLK_NUM_WIDTH (AM_STRIDE_BLK_NUM_UPPER-AM_STRIDE_BLK_NUM_LOWER+1)
#define AM_SRC_VECTOR_NUM_WIDTH (AM_SRC_VECTOR_NUM_UPPER-AM_SRC_VECTOR_NUM_LOWER+1)
#define AM_DST_VECTOR_NUM_WIDTH (AM_DST_VECTOR_NUM_UPPER-AM_DST_VECTOR_NUM_LOWER+1)
#define AM_SRC_VECTOR_SIZE_HEAD_WIDTH (AM_SRC_VECTOR_SIZE_HEAD_UPPER-AM_SRC_VECTOR_SIZE_HEAD_LOWER+1)
#define AM_DST_VECTOR_SIZE_HEAD_WIDTH (AM_DST_VECTOR_SIZE_HEAD_UPPER-AM_DST_VECTOR_SIZE_HEAD_LOWER+1)
#define AM_SRC_VECTOR_SIZE_BODY_WIDTH (AM_SRC_VECTOR_SIZE_BODY_UPPER-AM_SRC_VECTOR_SIZE_BODY_LOWER+1)
#define AM_DST_VECTOR_SIZE_BODY_WIDTH (AM_DST_VECTOR_SIZE_BODY_UPPER-AM_DST_VECTOR_SIZE_BODY_LOWER+1)

/*******************************************************************************
 * Active Message parameter bit masks
*******************************************************************************/

#define AM_PAYLOAD_SIZE_BITMASK ((power_64<2,AM_PAYLOAD_SIZE_WIDTH>()-1) << AM_PAYLOAD_SIZE_LOWER)
#define AM_SRC_BITMASK ((power_64<2,AM_SRC_WIDTH>()-1) << AM_SRC_LOWER)
#define AM_DST_BITMASK ((power_64<2,AM_DST_WIDTH>()-1) << AM_DST_LOWER)
#define AM_HANDLER_BITMASK ((power_64<2,AM_HANDLER_WIDTH>()-1) << AM_HANDLER_LOWER)
#define AM_TYPE_BITMASK ((power_64<2,AM_TYPE_WIDTH>()-1) << AM_TYPE_LOWER)
#define AM_HANDLER_ARGS_BITMASK ((power_64<2,AM_HANDLER_ARGS_WIDTH>()-1) << AM_HANDLER_ARGS_LOWER)
#define AM_TOKEN_BITMASK ((power_64<2,AM_TOKEN_WIDTH>()-1) << AM_TOKEN_LOWER)
#define AM_STRIDE_SIZE_BITMASK ((power_64<2,AM_STRIDE_SIZE_WIDTH>()-1) << AM_STRIDE_SIZE_LOWER)
#define AM_STRIDE_BLK_SIZE_BITMASK ((power_64<2,AM_STRIDE_BLK_SIZE_WIDTH>()-1) << AM_STRIDE_BLK_SIZE_LOWER)
#define AM_STRIDE_BLK_NUM_BITMASK ((power_64<2,AM_STRIDE_BLK_NUM_WIDTH>()-1) << AM_STRIDE_BLK_NUM_LOWER)
#define AM_SRC_VECTOR_NUM_BITMASK ((power_64<2,AM_SRC_VECTOR_NUM_WIDTH>()-1) << AM_SRC_VECTOR_NUM_LOWER)
#define AM_DST_VECTOR_NUM_BITMASK ((power_64<2,AM_DST_VECTOR_NUM_WIDTH>()-1) << AM_DST_VECTOR_NUM_LOWER)
#define AM_SRC_VECTOR_SIZE_HEAD_BITMASK ((power_64<2,AM_SRC_VECTOR_SIZE_HEAD_WIDTH>()-1) << AM_SRC_VECTOR_SIZE_HEAD_LOWER)
#define AM_DST_VECTOR_SIZE_HEAD_BITMASK ((power_64<2,AM_DST_VECTOR_SIZE_HEAD_WIDTH>()-1) << AM_DST_VECTOR_SIZE_HEAD_LOWER)
#define AM_SRC_VECTOR_SIZE_BODY_BITMASK ((power_64<2,AM_SRC_VECTOR_SIZE_BODY_WIDTH>()-1) << AM_SRC_VECTOR_SIZE_BODY_LOWER)
#define AM_DST_VECTOR_SIZE_BODY_BITMASK ((power_64<2,AM_DST_VECTOR_SIZE_BODY_WIDTH>()-1) << AM_DST_VECTOR_SIZE_BODY_LOWER)

#endif // SHOAL_INCLUDE_CONFIG_H_
