#if !defined(SHOAL_GASCORE_CONFIG_H_)
#define SHOAL_GASCORE_CONFIG_H_

#define AM_SHORT 0x1
#define AM_MEDIUM 0x2
#define AM_LONG 0x4
#define AM_VECTOR 0x6
#define AM_STRIDE 0x5
#define AM_FIFO 0x10
#define AM_ASYNC 0x20
#define AM_REPLY 0x40

#define H_EMPTY 0
#define H_ADD 2
#define H_WAIT 4

#define AM_SRC_UPPER 23
#define AM_SRC_LOWER 8
#define AM_DST_UPPER 39
#define AM_DST_LOWER 24
#define AM_PAYLOAD_SIZE_UPPER 51
#define AM_PAYLOAD_SIZE_LOWER 40
#define AM_HANDLER_UPPER 55
#define AM_HANDLER_LOWER 52
#define AM_TYPE_UPPER 7
#define AM_TYPE_LOWER 0
#define AM_HANDLER_ARGS_UPPER 63
#define AM_HANDLER_ARGS_LOWER 56
#define AM_TOKEN_UPPER 63
#define AM_TOKEN_LOWER 40

#define AM_STRIDE_SIZE_LOWER 0
#define AM_STRIDE_SIZE_UPPER 15
#define AM_STRIDE_BLK_SIZE_LOWER 16
#define AM_STRIDE_BLK_SIZE_UPPER 27
#define AM_STRIDE_BLK_NUM_LOWER 28
#define AM_STRIDE_BLK_NUM_UPPER 39

#define AM_SRC_VECTOR_NUM_LOWER 0
#define AM_SRC_VECTOR_NUM_UPPER 3
#define AM_DST_VECTOR_NUM_LOWER 4
#define AM_DST_VECTOR_NUM_UPPER 7
#define AM_SRC_VECTOR_SIZE_HEAD_LOWER 8
#define AM_SRC_VECTOR_SIZE_HEAD_UPPER 19
#define AM_DST_VECTOR_SIZE_HEAD_LOWER 20
#define AM_DST_VECTOR_SIZE_HEAD_UPPER 31
#define AM_SRC_VECTOR_SIZE_BODY_LOWER 0
#define AM_SRC_VECTOR_SIZE_BODY_UPPER 11
#define AM_DST_VECTOR_SIZE_BODY_LOWER 0
#define AM_DST_VECTOR_SIZE_BODY_UPPER 11

#define AM_PAYLOAD_SIZE AM_PAYLOAD_SIZE_UPPER,AM_PAYLOAD_SIZE_LOWER
#define AM_SRC AM_SRC_UPPER,AM_SRC_LOWER
#define AM_DST AM_DST_UPPER,AM_DST_LOWER
#define AM_HANDLER AM_HANDLER_UPPER,AM_HANDLER_LOWER
#define AM_TYPE AM_TYPE_UPPER,AM_TYPE_LOWER
#define AM_HANDLER_ARGS AM_HANDLER_ARGS_UPPER,AM_HANDLER_ARGS_LOWER
#define AM_TOKEN AM_TOKEN_UPPER,AM_TOKEN_LOWER

#define AM_TOKEN_WIDTH (AM_TOKEN_UPPER-AM_TOKEN_LOWER+1)

#define AM_STRIDE_SIZE AM_STRIDE_SIZE_UPPER,AM_STRIDE_SIZE_LOWER
#define AM_STRIDE_BLK_SIZE AM_STRIDE_BLK_SIZE_UPPER,AM_STRIDE_BLK_SIZE_LOWER
#define AM_STRIDE_BLK_NUM AM_STRIDE_BLK_NUM_UPPER,AM_STRIDE_BLK_NUM_LOWER

#define AM_SRC_VECTOR_NUM AM_SRC_VECTOR_NUM_UPPER,AM_SRC_VECTOR_NUM_LOWER
#define AM_DST_VECTOR_NUM AM_DST_VECTOR_NUM_UPPER,AM_DST_VECTOR_NUM_LOWER
#define AM_SRC_VECTOR_SIZE_HEAD AM_SRC_VECTOR_SIZE_HEAD_UPPER,AM_SRC_VECTOR_SIZE_HEAD_LOWER
#define AM_DST_VECTOR_SIZE_HEAD AM_DST_VECTOR_SIZE_HEAD_UPPER,AM_DST_VECTOR_SIZE_HEAD_LOWER
#define AM_SRC_VECTOR_SIZE_BODY AM_SRC_VECTOR_SIZE_BODY_UPPER,AM_SRC_VECTOR_SIZE_BODY_LOWER
#define AM_DST_VECTOR_SIZE_BODY AM_DST_VECTOR_SIZE_BODY_UPPER,AM_DST_VECTOR_SIZE_BODY_LOWER

#endif // SHOAL_GASCORE_CONFIG_H_
