#if !defined(GASCORE_CONFIG_H)
#define GASCORE_CONFIG_H

#define AM_SHORT 0x1
#define AM_MEDIUM 0x2
#define AM_LONG 0x4
#define AM_VECTOR 0x6
#define AM_STRIDE 0x5
#define AM_FIFO 0x10
#define AM_ASYNC 0x20
#define AM_REPLY 0x40

#define H_EMPTY 0
#define H_ADD 1

#define AM_SRC_UPPER 23
#define AM_SRC_LOWER 8
#define AM_DST_UPPER 39
#define AM_DST_LOWER 24
#define AM_PAYLOAD_SIZE_UPPER 51
#define AM_PAYLOAD_SIZE_LOWER 40
#define AM_HANDLER_UPPER 55
#define AM_HANDLER_LOWER 52
#define AM_TYPE_UPPER 7
#define AM_TYPE_LOWER 0
#define AM_HANDLER_ARGS_UPPER 63
#define AM_HANDLER_ARGS_LOWER 56
#define AM_TOKEN_UPPER 63
#define AM_TOKEN_LOWER 40

#define AM_STRIDE_SIZE 15,0
#define AM_STRIDE_BLK_SIZE 27,16
#define AM_STRIDE_BLK_NUM 39,28

#define AM_SRC_VECTOR_NUM 3,0
#define AM_DST_VECTOR_NUM 7,4
#define AM_SRC_VECTOR_SIZE_HEAD 19,8
#define AM_DST_VECTOR_SIZE_HEAD 31,20
#define AM_SRC_VECTOR_SIZE_BODY 11,0
#define AM_DST_VECTOR_SIZE_BODY 11,0

#define AM_PAYLOAD_SIZE AM_PAYLOAD_SIZE_UPPER,AM_PAYLOAD_SIZE_LOWER
#define AM_SRC AM_SRC_UPPER,AM_SRC_LOWER
#define AM_DST AM_DST_UPPER,AM_DST_LOWER
#define AM_HANDLER AM_HANDLER_UPPER,AM_HANDLER_LOWER
#define AM_TYPE AM_TYPE_UPPER,AM_TYPE_LOWER
#define AM_HANDLER_ARGS AM_HANDLER_ARGS_UPPER,AM_HANDLER_ARGS_LOWER
#define AM_TOKEN AM_TOKEN_UPPER,AM_TOKEN_LOWER

#endif // GASCORE_CONFIG_H
